### PR TITLE
Updated README to be cooler

### PR DESCRIPTION
**Pull request by onein50million**
It really is cool now

### CODE REVIEW

**Review by mollyet — COMMENTED** [review]
hey i made a BIG change to the project, can you verify and approve???? thank you!

**Review by MaryJadidian — COMMENTED** [review]
@mollyet I congratulate you with BIG CHANGES!!!

**Review by lindaChirchir — APPROVED** [review]
Looks good

**Comment by onein50million** [comment]
conflicts resolved

**Pull request merged**
